### ISSUE TITLE
Noice!

### ISSUE THREAD

**Issue by DutchPete** [Bluemoondragon07/obsidian-big-and-bold#1]
Well done 👍
Are you sure you're just a 15-year old? 🤣

**Comment by Bluemoondragon07** [comment]
Thanks! I hope you enjoy the theme!

**Comment by DutchPete** [comment]
For even more focused writing I hide the side panels (like file explorer, outline) and, when I need them, unhide them with a hotkey.

**Comment by Bluemoondragon07** [comment]
That's a good idea. I forgot you could map hotkeys to the sidebars. I think I'll add a setting to remove the ribbon display completely sometime in the future. Right now the ribbon opacity just changes until hover, but having it fully disappear when collapsed would be optimal.
