### ISSUE TITLE
Tables unstyled

### ISSUE THREAD

**Issue by cat-nash** [Bluemoondragon07/obsidian-big-and-bold#10]
Tables have reverted to an unstylised state.

![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/134531816/26a96c64-719a-4bc3-8a08-0e473c485a83)

* Tables remain to the left-hand side of the screen as opposed to the centre.
* Highlighting no longer works.

**Comment by Bluemoondragon07** [comment]
This has been fixed in the latest update; enjoy!
