### ISSUE TITLE
H1 Title Centered

### ISSUE THREAD

**Issue by OLH21** [Bluemoondragon07/obsidian-big-and-bold#11]
H1 Title are allways centered in this Theme wich is quite unusual as default setting
Is it possible to have an option to have them Align on the right like the other title level through the "Theme Setting"

**Comment by OLH21** [comment]
Quick and dirty fix with custom css snipet :

.markdown-rendered h1, .HyperMD-header-1 {
    text-align: left !important;
}

Don't know if it's the best selector to use but it seems to work

**Comment by Bluemoondragon07** [comment]
After the last update, there is now a quick option in Style Settings to have H1 left-aligned. Thank you for sharing with me the idea.
