### ISSUE TITLE
Paragraph/line spacing in code block

### ISSUE THREAD

**Issue by OLH21** [Bluemoondragon07/obsidian-big-and-bold#13]
In the code block the spacing between line ( ie paragraph) is way too big for standard code formatting. The spacing between lines should be different than regular text in notes.
![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/a701e32c-3125-49a6-8ea3-3c2d98265935)

**Comment by Bluemoondragon07** [comment]
I agree with you on this. I don't use code blocks too often, so I didn't realize the line height was being affected by the theme. Thanks for pointing this out! I will look at fixing this when I have the time.

**Comment by OLH21** [comment]
Quick and dirty fix , added a css snipet with :

.cm-s-obsidian .HyperMD-codeblock {
    padding-bottom: 0px !important;
    padding-top: 0px !important;
}

Don't know how your theme handle code but this seems to work witout any other effect

**Comment by Bluemoondragon07** [comment]
Thanks! That helps me a lot. I'll try to incorporate into an update later tonight.

**Comment by OLH21** [comment]
I am really not good with CSS an i learned a lot reading your theme, but still there is a lot of things i do not understand in the CSS class relative to Obsidian and how everything your theme work. still learning :)

**Comment by Bluemoondragon07** [comment]
Glad my theme helped up you learn, but I am definitely not anywhere close to being "fluent" in CSS either. I somewhat understand it, but it's all trial and error! We just need to keep practicing, and then we'll get it 😃

**Comment by OLH21** [comment]
Also i see that there is quite a diffirerence from the edit and read mode in code block ( color of text , left margin  and round corner ) 
I personnally prefer the Reading version 
![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/d4b4a8dc-f997-4cb7-a996-d916d86261e1)
compared to the editing one
![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/a279b083-dbe0-4cf3-a4f5-9877d719624e)

**Comment by OLH21** [comment]
Looks much hard to fix because with the same selctor as before 

.cm-s-obsidian .HyperMD-codeblock {
padding-bottom: 0px !important;
padding-top: 0px !important;
/* line-height: 2 !important; /* Changes the line height */
/* background-color: #f5f5f5; /* light grey background */
border: 1px solid #ddd; /* thin grey border */
border-radius: 5px; /* rounded corners */
/* font-family: 'Courier New', monospace; /* change the font to Courier New */
color: #f11414; /* red  text for test */

}

i get something like that 

![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/4c77a19a-1af9-4263-af84-3c2dd0f04258)

and the color of text is not changing !! 

lot to learn on how obsidian manage edit/read mode :)

**Comment by OLH21** [comment]
Couldn't adress the round corner but if iu change your theme code section to 


/* ----- GENERAL CODE BLOCKS ------ */

.markdown-rendered pre {
    border: 1px solid var(--background-modifier-border);
    box-shadow: var(--shadow-ui);
    padding: 2em;
}

.cm-s-obsidian .HyperMD-codeblock  {
    padding-top: 0px !important;
    padding-bottom: 0px !important;    
}

.cm-s-obsidian .HyperMD-codeblock * {
    margin-left: 30px;
    line-height: var(--custom-code-height);
    color: var(--text-normal);
  }

.markdown-rendered code {
    color: var(--text-normal);
 }

![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/470ce3e2-2561-4d74-9f6a-b130db4341e6)


and added a @setting in TYPOGRAPHY

    -
        id: main-text-heading
        title: Code Block
        type: heading
        level: 3
        collapsed: true
    -
        id: custom-code-height
        title: Code Height
        description: Control the line spacing in the code blocks
        type: variable-number-slider
        default: 1
        format: em
        min: 1
        max: 3
        step: 0.1

![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/dfb37a32-3103-4dc6-a0a9-fa940c50a0e9)

Never did a pull request before so maybe it's easier to past here ( i'll try to make one though)

**Comment by OLH21** [comment]
pull request donne hope it's good :)

**Comment by Bluemoondragon07** [comment]
Thank you so much for making the pull request! I apologize for the long wait, but I finally merged the changes with some slight modifications (I made it so that the custom line height affects the rendered codeblock in reading mode as well). Thank you so much for helping me improve the theme and enjoy the update!
