### ISSUE TITLE
Can support the "Auto card link" plugin?

### ISSUE THREAD

**Issue by i-iooi-i** [Bluemoondragon07/obsidian-big-and-bold#15]
![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/1827701/2bd6db8d-6d19-48fe-bf2a-caf45de7d258)
Hi, May I ask if you can support it“ https://github.com/nekoshita/obsidian-auto-card-link ”What about plugins?
The effect it displays now seems to be incorrect.

![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/1827701/767cc49a-fd7b-4f20-ba26-5bcb1c7e48aa)
I tried using other themes and they all displayed correctly.  
But I would prefer 'Big and Bold' to support it because I really like Big and Bold. 😊 THX~

**Comment by Bluemoondragon07** [comment]
Sure thing! I'll try to do it by the end of the day.

**Comment by i-iooi-i** [comment]
> Sure thing! I'll try to do it by the end of the day.

Thank you for your enthusiasm. Thank you very much. ♥

**Comment by Bluemoondragon07** [comment]
Done! Please update to the latest version and enjoy!

**Comment by i-iooi-i** [comment]
> Done! Please update to the latest version and enjoy!

![image](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/1827701/41c57781-7788-4f22-99c8-51516f7961b8)
Cool, it's working, thank you! 😻
