### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by DutchPete** [Bluemoondragon07/obsidian-big-and-bold#2]
2 Questions:

1. Your theme centers the image and adjusts the size. What can I put in a snippet to avoid that? I just want the image to be on the left and to adjust the size this way: `![[image.png|300]]`.
2. This `![right](sky.png)` does not work for me.

**Comment by Bluemoondragon07** [comment]
1. This snippet should do the trick:
```
.view-content .markdown-rendered img {
width: revert !important;
max-width: unset !important;
min-width: unset;
margin: 4em 1.5em;
display: revert;
}
```
2. I'm not sure why the `right` image is not working. Make sure the theme is updated to version 0.0.6 and check if the image is inside, directly before, or directly after a paragraph (sometimes the image will not float around headings or callouts). Also, see if there are any snippets enabled that might intervene with the images floating to the side. If the image is local, try `![[sky.png|right]]` With the snippet above, you may need to reduce the size of an image for the change to be visible. Let me know if the problem still persists.

**Comment by DutchPete** [comment]
Unfortunately the problem persists.

Re 1.: your snippet has no effect.
Re 2.: the theme is updated. The image is neither inside, nor directly before, nor directly after a paragraph. There are no interfering snippets. `![[sky.png|right]]` does not work.

**Comment by Bluemoondragon07** [comment]
1. I made an update to the theme a few seconds ago. Please update to version 1.1.6. It includes a Style Setting option to fix images. 
2. The image will only float if it is inside, directly before, or directly after a paragraph. Try putting it in the middle of a block of text. If it still does not work, try it with an external image instead. If the problem persists even after that, consider sending a screenshot of the image in both preview and source mode.

**Comment by DutchPete** [comment]
I updated to 1.1.6 and in Style Settings disabled both image toggles. The original size is now preserved, but the image is still centered.

Below are screenshots in source mode and live preview:

![image](https://user-images.githubusercontent.com/10794265/220968895-6d33d0d4-69ed-493f-b839-2ba945a2b89c.png)

![image](https://user-images.githubusercontent.com/10794265/220968954-9771cc7f-52fb-4d89-a259-c329130e746a.png)

**Comment by Bluemoondragon07** [comment]
Hmm...
This is a hard one. I'm really not sure why the image is still centered. I notice that the background looks like a different color. Is it inside a callout?

Is it just this one image or all images in the vault behaving like this? If it is this one image only, try  `![[Jacinda-Ardern.png|left]]`. That might fix it in this one case.

If it's all images in the vault, try disabling every one of your snippets and seeing if anything about the image changes. If nothing changes, then I'll have to check if it's something interfering inside the theme. It works perfectly fine in my vault with snippets disabled.

If all that fails, check your version of Obsidian. Make sure it is updated. 

Otherwise, I'm not sure what the cause of the misaligned images could be.

**Comment by Bluemoondragon07** [comment]
I tested it in the sandbox vault, and it works on my device. The last thing I can think of is that it *could* be your installer version. My installer version is at v1.1.9.

**Comment by DutchPete** [comment]
I am using the same installed version.

**Comment by Bluemoondragon07** [comment]
Aw, man. I have no idea what could be causing the issues, then. Is Style Settings up to date?

If so, then I'm clueless. Right now it seems to only be affecting your vault, so I'm thinking it might be something *in* the vault rather than the theme.

**Comment by DutchPete** [comment]
OK, we'll have to leave it that for now. I'll see if there is a way with CSS to force it comply. I don't think it is a vault problem because it does not happen with most other themes I tried/use.

The only other one it happens with is Maple, but this solves it:

```css
body.image-alt .view-content img:not(.emoji) {
  margin: 0;
}
```

Unfortunately, that does not work for Big-and-Bold.

**Comment by Bluemoondragon07** [comment]
I changed the way images display in Preview Mode a little bit in the newest update. Let me know if this fixes the issue.

**Comment by DutchPete** [comment]
Thank you for giving it another try.

However, it does not work. Having said that, though, it seems we are talking cross purposes. I am talking about Live Preview, you are talking about Reading mode.

**Comment by Bluemoondragon07** [comment]
Oh, that's it! This whole time I've been trying to fix *Reading Mode*! My bad. I know what to do now.

**Comment by DutchPete** [comment]
No way, it is NOT your bad!! It is my bad, I should have mentioned it from the outset.
I sincerely apologize for making you lose your time

**Comment by Bluemoondragon07** [comment]
No, you *did* mention Live Preview earlier. I just got the two terms mixed up somewhere.

**Comment by DutchPete** [comment]
Thank you for fixing this.
