### ISSUE TITLE
Difficult to get into bottom row of a table

### ISSUE THREAD

**Issue by DutchPete** [Bluemoondragon07/obsidian-big-and-bold#3]
I have a note with a number of tables, but the last table in that note poses a difficulty.
When I try to enter into a cell in the table's bottom row, the cursor jumps outside the table.

https://user-images.githubusercontent.com/10794265/221831363-33ed1489-d59e-4c73-b4d0-c1534eb01ad1.mov

**Comment by Bluemoondragon07** [comment]
That's not good. Thanks for submitting this issue; I'll look into this.

**Comment by DutchPete** [comment]
Thank you for fixing this.
