### ISSUE TITLE
Some small proposals

### ISSUE THREAD

**Issue by i-iooi-i** [Bluemoondragon07/obsidian-big-and-bold#4]
![image](https://user-images.githubusercontent.com/1827701/222975443-130414ec-5260-4ecb-acf1-70a6c5b5162b.png)

Hey, hello, I really like this theme. It's different in the store.
I have been using it for a day and have encountered some problems when using it.
Actually, it may not be a problem 😂

Can we consider adding a switch to turn off shadows in the future?
When the whole page is of flat design, such an effect will not look beautiful.

![image](https://user-images.githubusercontent.com/1827701/222975583-885ea11c-c9ed-4bcc-99b1-33eea0c13059.png)
When using banners, this obvious shadow problem also occurs. https://github.com/noatpad/obsidian-banners
I don't think this is a mistake, but it doesn't look very beautiful. 😊

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/222975702-e621d2c7-ad11-45b3-8cd8-40f8aeb0914f.png)
In addition, in the system of WIN11, the switch color is not consistent with the theme. This seems to be a problem. 😂
In short, I like your theme very much. It's really special.🚀

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/222976953-a176fa66-cc5d-4b86-90e9-b8e0667717aa.png)
In addition, can you consider adding a default height option in the future.
Because a blank area will appear in the top area, and in some cases, the displayed text will be incomplete.

![image](https://user-images.githubusercontent.com/1827701/222976976-ece1c060-f3cb-42bf-a904-aa7d4f386687.png)
The default theme seems to render better.

**Comment by Bluemoondragon07** [comment]
Thank you for pointing these out. I don't use the native window or banners plug-in, so I would never have noticed these things on my own. I think an option to hide shadows is also a really good idea . I will get right to fixing these!

I don't recognise the panel layout for the lists in the pictures on the bottom, though. Are they made with HTML?

**Comment by Bluemoondragon07** [comment]
Please update to the newest version. I have added all of your requests.

1. To turn off shadows, go to `Settings > Style Settings > Big & Bold > Workspace`. 
2. Banners are now full-width, do not have a hover effect, and do not have a box shadow or round corners.
3. The window frame buttons are now transparent to match the color behind it.
4. At first the lists confused me, but then I realized it was on a canvas file. I have removed the unnecessary margins inside the cards.

Please enjoy the update ⭐

**Comment by i-iooi-i** [comment]
Thank you for your theme appearance. It's great for me now. 😊😊😊
