### ISSUE TITLE
【feature request】support more condense and static Full calendar interface

### ISSUE THREAD

**Issue by Ravenclawer** [Bluemoondragon07/obsidian-big-and-bold#7]
This is a great theme, thank you for creating it. I use the full calendar plugin daily to arrange my schedule, but when I change to this theme the interface of the full calendar will change and become less compact and more dynamic which is not good for displaying as much information in the limited space. 
So, it would be great if you can make an option to keep the default or a more compact and static UI for opening the full calendar with the theme.

**Comment by Ravenclawer** [comment]
![image](https://user-images.githubusercontent.com/73892411/230021913-652bb3ca-e3a6-4c7a-bbe5-e1d7f34ca51e.png)
gap appeared after shift to big & bold

**Comment by Ravenclawer** [comment]
gap disappeared after switch to other theme 
![image](https://user-images.githubusercontent.com/73892411/230022280-e4225b79-43df-418d-adeb-c844c2bb28ed.png)

**Comment by Bluemoondragon07** [comment]
Thanks for letting me know about this design flaw. Sorry about the late reply, I've been kind of busy. I'll certainly fix this in the next update!

**Comment by Bluemoondragon07** [comment]
Fixed in the latest update. Enjoy!
