### ISSUE TITLE
Folder and file move to the left

### ISSUE THREAD

**Issue by OLH21** [Bluemoondragon07/obsidian-big-and-bold#9]
Each time i clic on a folder it moves all the files and folder a little bit to the left and after a few clic the diseapear under the right limit of the column 

![Capture d’écran 2023-05-24 165524](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/fee7afce-1889-41aa-b54c-673e2620ddb5)
![Capture d’écran 2023-05-24 165446](https://github.com/Bluemoondragon07/obsidian-big-and-bold/assets/47591060/72e8a1cf-1ff0-4074-a6be-35d87f9f534a)

I hope this can be fixed because I just LOVE this theme it's one of the reason i choose obsidian !!!

**Comment by Bluemoondragon07** [comment]
This has been fixed in the latest update; enjoy!
